name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Add package repository
        run: sudo add-apt-repository ppa:kelleyk/emacs

      - name: Update package list
        run: sudo apt-get update
        
      - name: Install Emacs
        run: sudo apt-get install emacs28-nox --yes

      - name: Build the site
        run: make website

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs
